version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
offroad = true
mcwdoors = true
mcwfences = true
farmersdelight = true
create_new_age = true
terra_curio = true
create_factory = true
tfmg = true
arsdelight = true
mcwwindows = true
plushables = true
yungscavebiomes = true
create = true
aeronautics = true
puddleflood = true
createcasing = true
mcwstairs = true
simulated = true
stellaris = true
refurbished_furniture = true
easyanvils = true
hexerei = true
minecraft = true
copycats = true
reestrogen = true
dragoncare = true
lootr = true
create_connected = true
iceandfire = true
just_blahaj = true
mcwfurnitures = true
origins = true
mcwbridges = true
mcwtrpdoors = true
ars_nouveau = true
tacz = true
treechop = true
neoorigins = true
